### ISSUE TITLE
Use s3-streamlogger with DigitalOcean Spaces

### ISSUE THREAD

**Issue by StriderRanger** [Coggle/s3-streamlogger#23]
I am trying to use s3-streamlogger along with DigitalOcean Spaces with the following code:

```
import { S3StreamLogger } from 's3-streamlogger';

const s3Stream = new S3StreamLogger({
  bucket: "mybucket",
  config: {
    endpoint: "sfo2.digitaloceanspaces.com",
  },
  access_key_id: "MY_ACCESS_KEY",
  secret_access_key: "MY_SECRET_KEY"
});

s3Stream.write("hello S3");
```

But I keep getting desperately this error: 

```
D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

InvalidArgument: null
    at Request.extractError (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\services\s3.js:582:35)
    at Request.callListeners (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\sequential_executor.js:109:20)
    at Request.emit (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\sequential_executor.js:81:10)
    at Request.emit (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\sequential_executor.js:119:18)
    at Request.emit (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\sequential_executor.js:81:10)
    at Request.emit (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (D:\PATH_TO_MY_PROJECT\node_modules\aws-sdk\lib\request.js:38:9)
[nodemon] app crashed - waiting for file changes before starting...
```
Any Idea about the InvalidArgument exception?

Thank you very much for your time!

**Comment by autopulated** [comment]
I can’t see any obvious problems with the configuration, it seems like the error could possibly be caused if the bucket specified didn’t exist, or the endpoint wasn’t accessible.

Have you tried making requests to your bucket using the AWS sdk with the same config?

**Comment by StriderRanger** [comment]
Thank you for your response.

I succeeded to upload a simple text file with the same credentials:

```
import AWS from 'aws-sdk';

const spacesEndpoint = new AWS.Endpoint('sfo2.digitaloceanspaces.com');
const s3 = new AWS.S3({
    endpoint: spacesEndpoint,
    accessKeyId: 'MY_ACCESS_KEY',
    secretAccessKey: 'MY_SECRET_KEY'
});

var params = {
    Body: "The contents of the file",
    Bucket: "mybucket",
    Key: "file.txt",
};

s3.putObject(params, function(err, data) {
    if (err) console.log(err, err.stack);
    else     console.log(data);
});
```
I am still investigating why it is not working with s3-streamlogger

**Comment by StriderRanger** [comment]
I tried withe the  `AWS.Endpoint('sfo2.digitaloceanspaces.com')`  endpoint but I am still getting the same error:

```
import   AWS              from 'aws-sdk';
import { S3StreamLogger } from 's3-streamlogger';

const s3Stream = new S3StreamLogger({
  bucket: "doublef",
  config: {
    endpoint: new AWS.Endpoint('sfo2.digitaloceanspaces.com'),
  },
  access_key_id: "CZ6MOV3O67ETZ7BTLGMC",
  secret_access_key: "mFr0oBxs8fHpivKVz9E9Edp8E2WXHQ0UeDBC4G4kwLY"
});

s3Stream.write("hello S3");
```

**Comment by StriderRanger** [comment]
it worked by adding the `tags` parameter:

```
import { S3StreamLogger } from 's3-streamlogger';

const s3Stream = new S3StreamLogger({
  bucket: "mybucket",
  config: {
    endpoint: 'nyc3.digitaloceanspaces.com'
  },
  access_key_id: "MY_ACCESS_KEY",
  secret_access_key: "MY_SECRET_KEY",
  tags: {type: "error", project: "doublef"}
});

s3Stream.write("hello S3");
```

**Comment by autopulated** [comment]
It seems that digital ocean spaces produces an error if an empty set of tags is passed (which is what will be set by `s3-streamlogger` if no tags are provided, as opposed to not setting tags at all). You might want to report that to digital ocean as an incompatibility between themselves and S3.

btw you pasted your secret key above, I'm not sure if you noticed? You should probably change that if you didn't already!

**Comment by StriderRanger** [comment]
thank you for alarming me. I don't understand how it comes to pass since I read the comment at least once before posting it, and what's more: all was as clear as day lol! ... it was a temporary bucket and it is already deleted along with the keys, so no harm is done :) 
Otherwise I will report this incompatibility to digital ocean, and post any relevant or helpful answer here.
Thanks :)

**Comment by mster81** [comment]
While an older topic, I think the docs should maybe point this out, had a similar issue with linode. 

1) Add docs that talk about setting the endpoint
2) Setting the tags 

After setting the endpoint in configs and the tags it works like a charm!
