### ISSUE TITLE
RequestTimeout error

### ISSUE THREAD

**Issue by raeesaa** [Coggle/s3-streamlogger#4]
Hi,

I am getting following error once in a while with s3-streamlogger

```

/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:30
throw err;
^
RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
at Request.extractError (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/services/s3.js:322:35)
at Request.callListeners (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:595:14)
at Request.transition (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:21:10)
at AcceptorStateMachine.runTo (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:37:9)
at Request.<anonymous> (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:597:12)
at Request.callListeners (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:595:14)
at Request.transition (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:21:10)
at AcceptorStateMachine.runTo (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/Users/xxxxxx/Documents/xxxxx/node_modules/s3-streamlogger/node_modules/aws-sdk/lib/request.js:37:9)

```

I understand from logs that connection to S3 is getting closed due to idle connection. Is there any way to keep this connection always open?

Thanks,
Raeesaa

**Comment by autopulated** [comment]
The connection to s3 is re-opened each time the log is up-loaded (there isn't a persistent connection). So I think this is something associated with an individual upload attempt. The comments on this issue: https://github.com/aws/aws-sdk-js/issues/281 suggest that retrying the upload is the solution.

It isn't clear to me from the backtrace whether the error is being correctly propagated to S3StreamLogger though – Do you have a handler attached to the error event on the S3StreamLogger stream? (If so does that get triggered when this happens?)

**Comment by raeesaa** [comment]
No I don't have handler attached to error event yet. I'll try adding it and
check.

Regards,
Raeesaa

**Comment by raeesaa** [comment]
@autopulated I am using s3-streamlogger with Winston. Can you please help me in adding error handler to it? I am finding it little difficult to figure out how to do that from existing README file.

**Comment by autopulated** [comment]
Sure, this should work:

```js
var winston        = require('winston');
var S3StreamLogger = require('s3-streamlogger').S3StreamLogger;

var s3_stream = new S3StreamLogger({
             bucket: "mys3bucket",
      access_key_id: "...",
  secret_access_key: "..."
});

s3_stream.on('error', function(err){
    // there was an error!
});

var logger = new (winston.Logger)({
  transports: [
    new (winston.transports.File)({
      stream: s3_stream
    })
  ]
});

logger.info('Hello Winston!');
```

**Comment by autopulated** [comment]
Just to confirm, we've now reproduced this, and that attaching an error hander as described prevents this from being fatal.

I'll update the readme.
